name: Konfigured
description: Prevent bad configuration files in your pull request
author: Cristopher Namchee
inputs:
  token:
    description: GitHub access token
    required: true
  newline:
    description: Requires final newline for all configuration files
    required: false
    default: false
  include:
    description: Files to be validated
    required: false
    default: ''
runs:
  using: docker
  image: "Dockerfile"
branding:
  icon: "settings"
  color: "white"